---
- name: Test starship executable
  ansible.builtin.stat:
    path: "/usr/local/bin/starship"
  register: starship

- name: Download and install starship
  become: true
  when: not starship.stat.exists
  block:
    - name: Download starship install script
      ansible.builtin.get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/install.sh
        mode: "0755"

    - name: Install starship
      ansible.builtin.command:
        cmd: sh /tmp/install.sh -y
      changed_when: true

    - name: Remove starship install file
      ansible.builtin.file:
        path: /tmp/install.sh
        state: absent

- name: Ensure the .zshrc_local file exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.zshrc_local"
    state: touch
    mode: "0600"
    modification_time: preserve
    access_time: preserve

- name: Fill the .zshrc_local
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts['user_dir'] }}/.zshrc_local"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - starship.rs"
    block: |
      # Starship.rs
      eval "$(starship init zsh)"
