---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install packages
      ansible.builtin.apt:
        name:
          - curl
        state: present
